=== balika011/lge_webos_kernel/drivers/mtk/target/mt53xx_com/53xx_com_driver/drv_cust/compal/QTY_DEFAULT/syntax_10.xsd
<!-- <?xml version="1.0" encoding="UTF-8"?> -->
<!-- edited with XMLSpy v2006 sp2 U (http://www.altova.com) by Cosh (MX) -->
<xs:schema xmlns:xs="http://www.w3.org/2001/XMLSchema" elementFormDefault="qualified">
	<!-- definition of index -->
	<xs:simpleType name="indextype">
		<xs:restriction base="xs:integer">
			<xs:minInclusive value="0"/>
			<xs:maxInclusive value="31"/>
		</xs:restriction>
	</xs:simpleType>
	<!-- definition of address -->
	<xs:simpleType name="valuetype">
		<xs:restriction base="xs:string">
			<xs:minLength value="1"/>
			<xs:maxLength value="8"/>
			<xs:pattern value="[0-9a-fA-F]*"/>
		</xs:restriction>
	</xs:simpleType>
	<!-- definition of access -->
	<xs:simpleType name="accesstype">
		<xs:restriction base="xs:string">
			<xs:enumeration value="82_xdata"/>
			<xs:enumeration value="82_vdoin1"/>
			<xs:enumeration value="82_tve"/>
			<xs:enumeration value="82_vdoin2"/>
			<xs:enumeration value="82_vdoin3"/>
			<xs:enumeration value="82_i2c"/>
			<xs:enumeration value="82_dsp"/>
			<xs:enumeration value="82_dspdec"/>
			<xs:enumeration value="82_dspenc"/>
			<xs:enumeration value="82_dsptxc"/>
			<xs:enumeration value="82_dspcomm"/>  
			<xs:enumeration value="8226_dir"/>
			<xs:enumeration value="8226_risc"/>
			<xs:enumeration value="8226_riscdram"/>  
			<xs:enumeration value="82_idata"/>
			<xs:enumeration value="82_drambyte"/>
			<xs:enumeration value="82_dramdword"/>
			<xs:enumeration value="82_i2c_extend"/>
			<xs:enumeration value="53_direct"/>
			<xs:enumeration value="53_82_xdata"/>
			<xs:enumeration value="53_82_vdoin1"/>
			<xs:enumeration value="53_82_vdoin2"/>
			<xs:enumeration value="53_82_vdoin3"/>
		</xs:restriction>
	</xs:simpleType>
	<!-- definition of sign -->
	<xs:simpleType name="signtype">
		<xs:restriction base="xs:string">
			<xs:enumeration value="signed"/>
			<xs:enumeration value="unsigned"/>
		</xs:restriction>
	</xs:simpleType>
	<!-- definition of base -->
	<xs:simpleType name="basetype">
		<xs:restriction base="xs:string">
			<xs:enumeration value="bin"/>
			<xs:enumeration value="dec"/>
			<xs:enumeration value="hex"/>
		</xs:restriction>
	</xs:simpleType>
	<!-- definition of Pair -->
	<xs:complexType name="pairtype">
		<xs:sequence>
			<xs:element name="desc" type="xs:string"/>
			<xs:element name="value" type="valuetype"/>
		</xs:sequence>
	</xs:complexType>
	<!-- definition of Data -->
	<xs:complexType name="datatype">
		<xs:sequence>
			<xs:element name="type" type="accesstype"/>
			<xs:element name="addr1" type="valuetype" default="0"/>
			<xs:element name="addr2" type="valuetype"/>
			<xs:element name="upper" type="indextype"/>
			<xs:element name="lower" type="indextype"/>
		</xs:sequence>
	</xs:complexType>
	<!-- definition of Field -->
	<xs:complexType name="fieldtype">
		<xs:sequence>
			<xs:element name="name" type="xs:string" default="noname"/>
			<xs:element name="sign" type="signtype" default="unsigned"/>
			<xs:element name="base" type="basetype" default="hex"/>
			<xs:element name="value" type="valuetype" default="0"/>
			<xs:element name="pair" type="pairtype" minOccurs="0" maxOccurs="unbounded"/>
			<xs:element name="data" type="datatype" maxOccurs="unbounded"/>
			<xs:element name="description" type="xs:string" default="" minOccurs="0" maxOccurs="1"/>
			<xs:element name="ro" type="valuetype" default="0" minOccurs="0" maxOccurs="1"/>
		</xs:sequence>
	</xs:complexType>
	<!-- definition of Group -->
	<xs:complexType name="grouptype">
		<xs:sequence>
			<xs:element name="name" type="xs:string" default="noname"/>
			<xs:element name="field" type="fieldtype" maxOccurs="unbounded"/>
		</xs:sequence>
	</xs:complexType>
	<!-- definition of Page -->
	<xs:complexType name="pagetype">
		<xs:sequence>
			<xs:element name="name" type="xs:string" default="noname"/>
			<xs:element name="group" type="grouptype" maxOccurs="unbounded"/>
		</xs:sequence>
	</xs:complexType>
	<!-- definition of Area-->
	<xs:complexType name="areatype">
		<xs:sequence>
			<xs:element name="alt" type="xs:string"/>
			<xs:element name="coords" type="xs:string"/>
			<xs:element name="href" type="xs:string"/>
		</xs:sequence>
	</xs:complexType>
	<!-- definition of Diagram -->
	<xs:complexType name="diagramtype">
		<xs:sequence>
			<xs:element name="name" type="xs:string" default="noname"/>
			<xs:element name="src" type="xs:string"/>
			<xs:element name="area" type="areatype" minOccurs="0" maxOccurs="unbounded"/>
		</xs:sequence>
	</xs:complexType>
	<!-- definition of Root -->
	<xs:complexType name="roottype">
		<xs:sequence>
			<xs:element name="version" type="xs:integer"/>
			<xs:element name="diagram" type="diagramtype" minOccurs="0" maxOccurs="unbounded"/>
			<xs:element name="page" type="pagetype" maxOccurs="unbounded"/>
		</xs:sequence>
	</xs:complexType>
	<!-- document root -->
	<xs:element name="root" type="roottype"/>
</xs:schema>

=== balika011/lge_webos_kernel/drivers/mtk/target/mt53xx_com/53xx_com_driver/drv_cust/Sony/QTY_Sony/MT5387_FlashPQ_default.xml
<?xml version="1.0" encoding="UTF-8" standalone="no" ?>
<root xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:noNamespaceSchemaLocation="syntax_10.xsd">

  <version>1</version>

  <page>
    <name>General</name>
    <group>
      <name>MAIN</name>
      <field>
        <name>CONTRAST</name>
        <sign>unsigned</sign>
        <base>hex</base>
        <value>88</value>
        <data>
          <type>53_direct</type>
          <addr1>0</addr1>
          <addr2>20027838</addr2>
          <upper>7</upper>
          <lower>0</lower>
        </data>
        <description></description>
        <ro>0</ro>
      </field>
      <field>
        <name>CONTRAST_HIBYTE</name>
        <sign>unsigned</sign>
        <base>hex</base>
        <value>0</value>
        <data>
          <type>53_direct</type>
          <addr1>0</addr1>
          <addr2>20027838</addr2>
          <upper>9</upper>
          <lower>8</lower>
        </data>
        <description></description>
        <ro>0</ro>
      </field>
      <field>
        <name>BRIGHTNESS</name>
        <sign>unsigned</sign>
        <base>hex</base>
        <value>7A</value>
        <data>
          <type>53_direct</type>
          <addr1>0</addr1>
          <addr2>20027838</addr2>
          <upper>26</upper>
          <lower>19</lower>
        </data>
        <description></description>
        <ro>0</ro>
      </field>
      <field>
        <name>SATURATION</name>
        <sign>unsigned</sign>
        <base>hex</base>
        <value>B0</value>
        <data>
          <type>53_direct</type>
          <addr1>0</addr1>
          <addr2>2002783c</addr2>
          <upper>7</upper>
          <lower>0</lower>
        </data>
        <description></description>
        <ro>0</ro>
      </field>
      <field>
        <name>SATURATION_HIBYTE</name>
        <sign>unsigned</sign>
        <base>hex</base>
        <value>0</value>
        <data>
          <type>53_direct</type>
          <addr1>0</addr1>
          <addr2>2002783c</addr2>
          <upper>9</upper>
          <lower>8</lower>
        </data>
        <description></description>
        <ro>0</ro>
      </field>
      <field>
        <name>HUE</name>
        <sign>unsigned</sign>
        <base>hex</base>
        <value>80</value>
        <data>
          <type>53_direct</type>
          <addr1>0</addr1>
          <addr2>2002783c</addr2>
          <upper>25</upper>
          <lower>18</lower>
        </data>
        <description></description>
        <ro>0</ro>
      </field>
    </group>
  </page>

  <page>
    <name>SHARP1</name>
    <group>
      <name>GAIN</name>
      <field>
        <name>LOW</name>
        <sign>unsigned</sign>
        <base>hex</base>
        <value>50</value>
        <data>
          <type>53_direct</type>
          <addr1>0</addr1>
          <addr2>20025340</addr2>
          <upper>7</upper>
          <lower>0</lower>
        </data>
        <description></description>
        <ro>0</ro>
      </field>
      <field>
        <name>LOW_NEG</name>
        <sign>unsigned</sign>
        <base>hex</base>
        <value>50</value>
        <data>
          <type>53_direct</type>
          <addr1>0</addr1>
          <addr2>20025344</addr2>
          <upper>7</upper>
          <lower>0</lower>
        </data>
        <description></description>
        <ro>0</ro>
      </field>
      <field>
        <name>MID</name>
        <sign>unsigned</sign>
        <base>hex</base>
        <value>54</value>
        <data>
          <type>53_direct</type>
          <addr1>0</addr1>
          <addr2>20025340</addr2>
          <upper>15</upper>
          <lower>8</lower>
        </data>
        <description></description>
        <ro>0</ro>
      </field>
      <field>
        <name>MID_NEG</name>
        <sign>unsigned</sign>
        <base>hex</base>
        <value>54</value>
        <data>
          <type>53_direct</type>
          <addr1>0</addr1>
          <addr2>20025344</addr2>
          <upper>15</upper>
          <lower>8</lower>
        </data>
        <description></description>
        <ro>0</ro>
      </field>
      <field>
        <name>HIGH</name>
        <sign>unsigned</sign>
        <base>hex</base>
        <value>5A</value>
        <data>
          <type>53_direct</type>
          <addr1>0</addr1>
          <addr2>20025340</addr2>
          <upper>23</upper>
          <lower>16</lower>
        </data>
        <description></description>
        <ro>0</ro>
      </field>
      <field>
        <name>HIGH_NEG</name>
        <sign>unsigned</sign>
        <base>hex</base>
        <value>5A</value>
        <data>
          <type>53_direct</type>
          <addr1>0</addr1>
          <addr2>20025344</addr2>
          <upper>23</upper>
          <lower>16</lower>
        </data>
        <description></description>
        <ro>0</ro>
      </field>
    </group>
    <group>
      <name>CORING</name>
      <field>
        <name>LOW_CORING</name>
        <sign>unsigned</sign>
        <base>hex</base>
        <value>1</value>
        <data>
          <type>53_direct</type>
          <addr1>0</addr1>
          <addr2>20025348</addr2>
          <upper>7</upper>
          <lower>0</lower>
        </data>
        <description></description>
        <ro>0</ro>
      </field>
      <field>
        <name>MID_CORING</name>
        <sign>unsigned</sign>
        <base>hex</base>
        <value>1</value>
        <data>
          <type>53_direct</type>
          <addr1>0</addr1>
          <addr2>20025348</addr2>
          <upper>15</upper>
          <lower>8</lower>
        </data>
        <description></description>
        <ro>0</ro>
      </field>
      <field>
        <name>HIGH_CORING</name>
        <sign>unsigned</sign>
        <base>hex</base>
        <value>1</value>
        <data>
          <type>53_direct</type>
          <addr1>0</addr1>
          <addr2>20025348</addr2>
          <upper>23</upper>
          <lower>16</lower>
        </data>
        <description></description>
        <ro>0</ro>
      </field>
    </group>
    <group>
      <name>LIMIT</name>
      <field>
        <name>LOW_LIMIT_POS</name>
        <sign>unsigned</sign>
        <base>hex</base>
        <value>FF</value>
        <data>
          <type>53_direct</type>
          <addr1>0</addr1>
          <addr2>2002534c</addr2>
          <upper>7</upper>
          <lower>0</lower>
        </data>
        <description></description>
        <ro>0</ro>
      </field>
      <field>
        <name>LOW_LIMIT_NEG</name>
        <sign>unsigned</sign>
        <base>hex</base>
        <value>FF</value>
        <data>
          <type>53_direct</type>
          <addr1>0</addr1>
          <addr2>20025350</addr2>
          <upper>7</upper>
          <lower>0</lower>
        </data>
        <description></description>
        <ro>0</ro>
      </field>
      <field>
        <name>MID_LIMIT_POS</name>
        <sign>unsigned</sign>
        <base>hex</base>
        <value>FF</value>
        <data>
          <type>53_direct</type>
          <addr1>0</addr1>
          <addr2>2002534c</addr2>
          <upper>15</upper>
          <lower>8</lower>
        </data>
        <description></description>
        <ro>0</ro>
      </field>
      <field>
        <name>MID_LIMIT_NEG</name>
        <sign>unsigned</sign>
        <base>hex</base>
        <value>FF</value>
        <data>
          <type>53_direct</type>
          <addr1>0</addr1>
          <addr2>20025350</addr2>
          <upper>15</upper>
          <lower>8</lower>
        </data>
        <description></description>
        <ro>0</ro>
      </field>
      <field>
        <name>HIGH_LIMIT_POS</name>
        <sign>unsigned</sign>
        <base>hex</base>
        <value>FF</value>
        <data>
          <type>53_direct</type>
          <addr1>0</addr1>
          <addr2>2002534c</addr2>
          <upper>23</upper>
          <lower>16</lower>
        </data>
        <description></description>
        <ro>0</ro>
      </field>
      <field>
        <name>HIGH_LIMIT_NEG</name>
        <sign>unsigned</sign>
        <base>hex</base>
        <value>FF</value>
        <data>
          <type>53_direct</type>
          <addr1>0</addr1>
          <addr2>20025350</addr2>
          <upper>23</upper>
          <lower>16</lower>
        </data>
        <description></description>
        <ro>0</ro>
      </field>
    </group>
    <group>
      <name>CLIP</name>
      <field>
        <name>CLIP_POS_EN</name>
        <sign>unsigned</sign>
        <base>hex</base>
        <value>0</value>
        <data>
          <type>53_direct</type>
          <addr1>0</addr1>
          <addr2>20025354</addr2>
          <upper>31</upper>
          <lower>31</lower>
        </data>
        <description></description>
        <ro>0</ro>
      </field>
      <field>
        <name>CLIP_NEG_EN</name>
        <sign>unsigned</sign>
        <base>hex</base>
        <value>0</value>
        <data>
          <type>53_direct</type>
          <addr1>0</addr1>
          <addr2>20025354</addr2>
          <upper>30</upper>
          <lower>30</lower>
        </data>
        <description></description>
        <ro>0</ro>
      </field>
      <field>
        <name>GB_CLIP_POS_EN_L</name>
        <sign>unsigned</sign>
        <base>hex</base>
        <value>1</value>
        <data>
          <type>53_direct</type>
          <addr1>0</addr1>
          <addr2>20025354</addr2>
          <upper>23</upper>
          <lower>23</lower>
        </data>
        <description></description>
        <ro>0</ro>
      </field>
      <field>
        <name>GB_CLIP_NEG_EN_L</name>
        <sign>unsigned</sign>
        <base>hex</base>
        <value>1</value>
        <data>
          <type>53_direct</type>
          <addr1>0</addr1>
          <addr2>20025354</addr2>
          <upper>22</upper>
          <lower>22</lower>
        </data>
        <description></description>
        <ro>0</ro>
      </field>
      <field>
        <name>GB_CLIP_POS_EN_M</name>
